title: Notes
description: Proofs and Derivations
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

linkedin_username: vivaan-gupta
    
mathjax: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex

