title: Hi, I am Vivaan
description: This is where I store my notes and other work
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex

