title: Notes
description: Proofs and Derivations
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
email: vivaan.gupta.1427@gmail.com
mathjax: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex

